language: node_js
node_js:
  - stable
install:
  - npm install
cache:
  directories:
    - node_modules
before_deploy:
  - hexo g
  - gulp
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: public
    target_branch: gh-pages
    on:
      branch: master